version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sales_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: sales_db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
